/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#eff4ff",
        "surface-container-highest": "#d3e4fe",
        "primary-fixed": "#e2dfff",
        "on-tertiary": "#ffffff",
        "outline": "#777587",
        "secondary-fixed": "#dae2fd",
        "outline-variant": "#c7c4d8",
        "on-primary-fixed": "#0f0069",
        "on-error-container": "#93000a",
        "on-background": "#0b1c30",
        "on-tertiary-container": "#67f4b7",
        "tertiary": "#005338",
        "on-surface-variant": "#464555",
        "surface-container-high": "#dce9ff",
        "inverse-primary": "#c3c0ff",
        "secondary": "#565e74",
        "tertiary-container": "#006e4b",
        "inverse-on-surface": "#eaf1ff",
        "surface-bright": "#f8f9ff",
        "on-secondary-fixed": "#131b2e",
        "surface-dim": "#cbdbf5",
        "on-secondary-container": "#5c647a",
        "surface-variant": "#d3e4fe",
        "on-primary-fixed-variant": "#3323cc",
        "on-tertiary-fixed": "#002113",
        "primary-container": "#4f46e5",
        "surface": "#f8f9ff",
        "primary-fixed-dim": "#c3c0ff",
        "on-secondary-fixed-variant": "#3f465c",
        "on-surface": "#0b1c30",
        "on-primary-container": "#dad7ff",
        "surface-container": "#e5eeff",
        "secondary-fixed-dim": "#bec6e0",
        "inverse-surface": "#213145",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "primary": "#3525cd",
        "surface-tint": "#4d44e3",
        "error": "#ba1a1a",
        "on-tertiary-fixed-variant": "#005236",
        "tertiary-fixed": "#6ffbbe",
        "background": "#f8f9ff",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#4edea3",
        "secondary-container": "#dae2fd"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "base": "4px",
        "sm": "8px",
        "container-max": "1280px",
        "lg": "24px",
        "xs": "4px",
        "2xl": "48px",
        "xl": "32px",
        "gutter": "24px",
        "md": "16px",
        "3xl": "64px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "code": ["Geist Mono", "monospace"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-md": ["30px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "code": ["14px", { lineHeight: "20px", fontWeight: "450" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }]
      }
    },
  },
  plugins: [],
}
